# Install the project to ~/.local/bin (CMAKE_INSTALL_PREFIX defined in cinstall.py/vinstall.py)
#
# Usage:
# 1a: When using conan, call $ python cinstall.py
# 1b: When using vcpkg, call $ python vinstall.py
# 2: $ python install.py
#

import json
import subprocess


# read presets generated by cinstall.py or vinstall.py
with open('CMakeUserPresets.json', 'r') as file:
    presets = json.load(file)

# find first non-Debug build preset
buildPresets = presets["buildPresets"]
for buildPreset in buildPresets:
    name = buildPreset["name"]
    configurePreset = buildPreset["configurePreset"]
    configuration = buildPreset["configuration"]
    if configuration != "Debug":
        #print(f"name {name} configuration {configuration}")

        # configure
        subprocess.run(f"cmake --preset {configurePreset}", shell=True)

        # build and install to CMAKE_INSTALL_PREFIX (e.g. ~/.local/bin)
        subprocess.run(f"cmake --build --preset {name} --target install", shell=True)
